charts:
- component: cilium
  chart: cilium
  version: 1.16.5
  source_url: https://helm.cilium.io/
  offline_repo_url: http://helm.lab.example:8081/helm/
  values_file: cilium-values.yaml
  checksum: 9e949d548c4c9272320fbed0923baf90b2033d21f92d7e9e8a7db950adee637a
- component: cert_manager
  chart: cert-manager
  version: v1.16.2
  source_url: https://charts.jetstack.io
  offline_repo_url: http://helm.lab.example:8081/helm/
  values_file: cert_manager-values.yaml
  checksum: 75071f90ee2634adcaffacd5d6b7a28a8ea0e16785992c1257daef8453a784f7
- component: ingress
  chart: ingress-nginx
  version: 4.11.3
  source_url: https://kubernetes.github.io/ingress-nginx
  offline_repo_url: http://helm.lab.example:8081/helm/
  values_file: ingress-values.yaml
  checksum: 12018aab383e6915ebcfc16c909d875d9b0d1f78337463fdb51c09bae5d01c5a
- component: argocd
  chart: argo-cd
  version: 7.7.8
  source_url: https://argoproj.github.io/argo-helm
  offline_repo_url: http://helm.lab.example:8081/helm/
  values_file: argocd-values.yaml
  checksum: 622a8aff67dcc42f800c62c87454349ea716bef54b3038715851304c552d391c
- component: postgres
  chart: postgresql
  version: 16.4.0
  source_url: https://charts.bitnami.com/bitnami
  offline_repo_url: http://helm.lab.example:8081/helm/
  values_file: postgres-values.yaml
  checksum: f726381330e02b63f93905dc463f54ff2ccee9683e1bea0f44f5b3a8c9d72b60
- component: prometheus
  chart: kube-prometheus-stack
  version: 66.2.1
  source_url: https://prometheus-community.github.io/helm-charts
  offline_repo_url: http://helm.lab.example:8081/helm/
  values_file: prometheus-values.yaml
  checksum: ac94d28640fbb4d0a489089ec1bf522558e5d103c71736e11c69b8bd07eaa918
- component: trivy
  chart: trivy
  version: 0.25.0
  source_url: https://aquasecurity.github.io/helm-charts/
  offline_repo_url: http://helm.lab.example:8081/helm/
  values_file: trivy-values.yaml
  checksum: 334e1d687a9e0ccd35624dbc011f019b2c55e96d3e7ade70b0f76943c33c08e9
helm_repo_dns: helm.lab.example
